In [1]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib

In [2]:

#import plotly.plotly as py
#import plotly.figure_factory as ff
#
#import pandas as pd
#
#py.sign_in('Gcav66', 'q0nMutWM7LU9R772A4wj')
#
#data = pd.read_json('https://cdn.rawgit.com/plotly/datasets/master/BulletData.json')
#
#fig = ff.create_bullet(
#    data, markers='markers', measures='measures',
#    ranges='ranges', subtitles='subtitle', titles='title',
#)
#py.iplot(fig, filename='bullet chart from a dataframe')

In [3]:
import dataiku
from dataiku import pandasutils as pdu
import pandas as pd

In [4]:
# Example: load a DSS dataset as a Pandas dataframe
mydataset = dataiku.Dataset("monthly_data_py_prep")
df = mydataset.get_dataframe()
df.head()

      DM EID DM FN DM LN  OFFICE # OFFICE NAME  Month  Year  WO DEALS  WX DEALS  WO Ees   WO MARGIN  WX Ees  WX RECUR ORDER  REV($PP)  FORECAST EES  # BPAs IN OFFICE EOM  TIER 1 BPAs  TIER 2 BPAs  TIER 3 BPAs  TIER 4 BPAs  TIER 5 BPAs  OPEN  HIRES  PROMOS  VOL# TERMS  INVOL# TERMS  PDPs  SOLD W/ LOYALTY  SOLD W/CHANNELS  SOLD W/ COI  SOLD W/CORP MKT  HOSTED EVENTS  DC Total  T1 DCs  T2 DCs  DC/BP Ratio  WO BP Total  T1 WOBPs  T2 WOBPs  WO Prop Total  WX BP Total  T1 WXBPs  T2 WXBPs  WX Prop Total   DM_NAME  office_number   REGION
0  2065934.0   Don  Alix       302   Phoenix 2      1  2018       1.0       NaN    22.0  154.636364     NaN             NaN       NaN            26                     9            7            2            0            1            0     0      0       0           0             0     0              1.0              0.0          0.0              1.0            0.0        28      21       5    25.000000            7         3         2              5            0         0         0              0  Don Alix            302  Western
1  2065934.0   Don  Alix       302   Phoenix 2      2  2018       2.0       NaN    30.0  177.166667     NaN             NaN       NaN            38                     9            7            2            0            1            0     0      0       0           0             0     0              2.0              0.0          1.0              NaN            2.0        31      15       6    32.258065           10         5         2              2            0         0         0              0  Don Alix            302  Western
2  2065934.0   Don  Alix       302   Phoenix 2      3  2018       4.5       NaN   141.0  161.879433     NaN             NaN       NaN            51                     8            7            2            0            1            0     1      0       0           1             0     3              2.0              0.0          1.0              1.0            2.0        67      39      13    31.343284           21        12         4             10            0         0         0              1  Don Alix            302  Western
3  2065934.0   Don  Alix       302   Phoenix 2      4  2018       3.0       NaN    42.0  164.785714     NaN             NaN       NaN            55                     8            7            2            0            1            0     1      0       0           0             0     0              0.0              0.0          0.0              1.0            5.0        47      19      15    40.425532           19         7         3             14            0         0         0              0  Don Alix            302  Western
4  2065934.0   Don  Alix       302   Phoenix 2      5  2018       1.5       NaN    47.0  176.936170     NaN             NaN       NaN            64                     9            7            2            0            1            0     0      1       0           0             0     0              1.5              1.0          0.0              NaN            2.0        60      34      18    40.000000           24        14         5              7            0         0         0              0  Don Alix            302  Western

In [5]:

import plotly.figure_factory as ff

import pandas as pd

In [6]:
s_df = df.pivot_table(values=['WO Ees', 'WO DEALS', 'DC Total', 'WO BP Total'], index=['DM_NAME', 'REGION'])
s_df['dc_meas'] = s_df['DC Total'].apply(lambda x: [round(x,2), round(x + 5,2)])
s_df['bp_meas'] = s_df['WO BP Total'].apply(lambda x: [round(x, 2), round(x + 5, 2)])
s_df['wo_ees_meas'] = s_df['WO Ees'].apply(lambda x: [round(x, 2), round(x + 5,2)])
s_df['wo_deal_meas'] = s_df['WO DEALS'].apply(lambda x: [round(x, 2), round(x + 5,2)])

s_df['dc_mark'] = s_df['DC Total'].max()
s_df['bp_mark'] = s_df['WO BP Total'].max()
s_df['wo_ee_mark'] = s_df['WO Ees'].max()
s_df['wo_deal_mark'] = s_df['WO DEALS'].max()



s_df['dc_range'] = s_df['DC Total'].apply(lambda x: [round(s_df['DC Total'].quantile(.25),2), 
                    round(s_df['DC Total'].quantile(.5),2), round(s_df['DC Total'].quantile(.75),2)])
s_df['bp_range'] = s_df['WO BP Total'].apply(lambda x: [round(s_df['WO BP Total'].quantile(.25),2), 
                    round(s_df['WO BP Total'].quantile(.5),2), round(s_df['WO BP Total'].quantile(.75),2)])
s_df['wo_ees_range'] = s_df['WO Ees'].apply(lambda x: [round(s_df['WO Ees'].quantile(.25),2), 
                    round(s_df['WO Ees'].quantile(.5),2), round(s_df['WO Ees'].quantile(.75),2)])
s_df['wo_deals_range'] = s_df['WO DEALS'].apply(lambda x: [round(s_df['WO DEALS'].quantile(.25),2), 
                    round(s_df['WO DEALS'].quantile(.5),2), round(s_df['WO DEALS'].quantile(.75),2)])

s_df = s_df.drop(['DC Total', 'WO BP Total', 'WO Ees', 'WO DEALS'], axis=1)
for x in ['dc_mark', 'bp_mark', 'wo_ee_mark', 'wo_deal_mark']:
    s_df[x] = s_df[x].apply(lambda x: [x])
s_df.reset_index(level=0, inplace=True)
s_df.reset_index(level=0, inplace=True)
rep_names = [x for x in s_df.DM_NAME.unique()]

In [ ]:
import dash
import dash_core_components as dcc
import dash_html_components as html

external_stylesheets = ['https://codepen.io/chriddyp/pen/bWLwgP.css']


app = dash.Dash(__name__, external_stylesheets=external_stylesheets)

app.layout = html.Div(children=[
    html.H1(children='Insperity Scorecard'),

    html.Label(children='Region'),

    dcc.RadioItems(
        id='region-dropdown',
        options=[{'label': k, 'value': k} for k in s_df.REGION.unique()],
        value='Eastern'
    ),
    html.Hr(),

    html.Label('Sales Reps'),

    dcc.Dropdown(id='reps_by_region'),
    html.Hr(),

    html.H3(children='WO Deals'),
    dcc.Graph(id='wo-deal'),
    html.H3(children='WO EEs'),
    dcc.Graph(id='wo-ees'),
    html.H3(children='DCs'),
    dcc.Graph(id='dc'),
    html.H3(children='BPs'),
    dcc.Graph(id='bp')

])

@app.callback(
    dash.dependencies.Output('reps_by_region', 'options'),
    [dash.dependencies.Input('region-dropdown', 'value')])

def set_rep_options(selected_region):
    return [{'label': i, 'value': i} for i in s_df[s_df.REGION == selected_region]['DM_NAME'].unique()]


@app.callback(
    dash.dependencies.Output('reps_by_region', 'value'),
    [dash.dependencies.Input('reps_by_region', 'options')])
def set_rep_value(available_options):
    return available_options[0]['value']

#update first bullet
@app.callback(
    dash.dependencies.Output('wo-deal', 'figure'),
    [dash.dependencies.Input('reps_by_region', 'value')])

def build_graph_one(Rep):
    plot_df = s_df[s_df['DM_NAME'] == Rep]
    return ff.create_bullet(plot_df, markers='wo_deal_mark', measures='wo_deal_meas',
            ranges='wo_deals_range', titles="DM_NAME")

#update second bullet
@app.callback(
    dash.dependencies.Output('wo-ees', 'figure'),
    [dash.dependencies.Input('reps_by_region', 'value')])

def build_graph_two(Rep):
    plot_df = s_df[s_df['DM_NAME'] == Rep]
    return ff.create_bullet(plot_df, markers='wo_ee_mark', measures='wo_ees_meas',
            ranges='wo_ees_range', titles="DM_NAME")

#update third bullet
@app.callback(
    dash.dependencies.Output('dc', 'figure'),
    [dash.dependencies.Input('reps_by_region', 'value')])

def build_graph_three(Rep):
    plot_df = s_df[s_df['DM_NAME'] == Rep]
    return ff.create_bullet(plot_df, markers='dc_mark', measures='dc_meas',
            ranges='dc_range', titles="DM_NAME")


#update four bullet
@app.callback(
    dash.dependencies.Output('bp', 'figure'),
    [dash.dependencies.Input('reps_by_region', 'value')])

def build_graph_four(Rep):
    plot_df = s_df[s_df['DM_NAME'] == Rep]
    return ff.create_bullet(plot_df, markers='bp_mark', measures='bp_meas',
            ranges='bp_range', titles="DM_NAME")



if __name__ == '__main__':
    app.run_server(debug=False, threaded=False, port=8051)

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off

 * Running on http://127.0.0.1:8051/ (Press CTRL+C to quit)