In [1]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib

In [2]:
import dataiku
from dataiku import pandasutils as pdu
import pandas as pd

In [7]:
# Example: load a DSS dataset as a Pandas dataframe
mydataset = dataiku.Dataset("Monthly_Office_Data_with_DM")
modf = mydataset.get_dataframe()

In [8]:
modf.head()

      DM EID DM FN DM LN  OFFICE # OFFICE NAME  Month  Year  WO DEALS  WX DEALS  WO Ees   WO MARGIN  WX Ees  WX RECUR ORDER  REV($PP)  FORECAST EES  # BPAs IN OFFICE EOM  TIER 1 BPAs  TIER 2 BPAs  TIER 3 BPAs  TIER 4 BPAs  TIER 5 BPAs  OPEN  HIRES  PROMOS  VOL# TERMS  INVOL# TERMS  PDPs  SOLD W/ LOYALTY  SOLD W/CHANNELS  SOLD W/ COI  SOLD W/CORP MKT  HOSTED EVENTS  DC Total  T1 DCs  T2 DCs  DC/BP Ratio  WO BP Total  T1 WOBPs  T2 WOBPs  WO Prop Total  WX BP Total  T1 WXBPs  T2 WXBPs  WX Prop Total
0  2065934.0   Don  Alix       302   Phoenix 2      1  2018       1.0       NaN    22.0  154.636364     NaN             NaN       NaN            26                     9            7            2            0            1            0     0      0       0           0             0     0              1.0              0.0          0.0              1.0            0.0        28      21       5    25.000000            7         3         2              5            0         0         0              0
1  2065934.0   Don  Alix       302   Phoenix 2      2  2018       2.0       NaN    30.0  177.166667     NaN             NaN       NaN            38                     9            7            2            0            1            0     0      0       0           0             0     0              2.0              0.0          1.0              NaN            2.0        31      15       6    32.258065           10         5         2              2            0         0         0              0
2  2065934.0   Don  Alix       302   Phoenix 2      3  2018       4.5       NaN   141.0  161.879433     NaN             NaN       NaN            51                     8            7            2            0            1            0     1      0       0           1             0     3              2.0              0.0          1.0              1.0            2.0        67      39      13    31.343284           21        12         4             10            0         0         0              1
3  2065934.0   Don  Alix       302   Phoenix 2      4  2018       3.0       NaN    42.0  164.785714     NaN             NaN       NaN            55                     8            7            2            0            1            0     1      0       0           0             0     0              0.0              0.0          0.0              1.0            5.0        47      19      15    40.425532           19         7         3             14            0         0         0              0
4  2065934.0   Don  Alix       302   Phoenix 2      5  2018       1.5       NaN    47.0  176.936170     NaN             NaN       NaN            64                     9            7            2            0            1            0     0      1       0           0             0     0              1.5              1.0          0.0              NaN            2.0        60      34      18    40.000000           24        14         5              7            0         0         0              0

In [6]:
mydataset = dataiku.Dataset("DM_OFFICE_REGION")
dmdf = mydataset.get_dataframe()

In [9]:
dmdf.head()

         DIST_MGR                OFFICE   REGION  Avg Margin % DM  AVG M+R DM
0  Abdiel Sanchez    0504 Los Angeles 4  Western         0.025810  149.186325
1     Allen Cohen    4403 San Antonio 1  Central         0.027179  144.152838
2     Andy Cullen  3701 Oklahoma City 1  Central         0.023632  156.728818
3      Bill Brown         4404 Dallas 1  Central         0.024932  179.184653
4       Bill Hamm         4406 Dallas 2  Central         0.028486  191.429496